### ISSUE TITLE
Issue with having more than one collections

### ISSUE THREAD

**Issue by ashBabu** [raviriley/agency-jekyll-theme#86]
Hi, 
I would like to add more than one `collections` in [_config.yaml](https://github.com/xTent-robotics/xTent-robotics.github.io/blob/video-slider_ash/_config.yml#L33). The following is what I did
```
collections:
  applications:
    output: true
  videos:
    output: true
    order:
      - xta_motion.md
      - xta_sim.md
      - pipe_concept.md
     
collections_dir: collections_xtent
```
In the `collections_xtent` directory, I have added two directories,  `_applications` and `_videos`, and a few markdown files. Then I added [applications.html](https://github.com/xTent-robotics/xTent-robotics.github.io/blob/video-slider_ash/_includes/applications.html) and [videos.html](https://github.com/xTent-robotics/xTent-robotics.github.io/blob/video-slider_ash/_includes/videos.html). These files are copied from the already provided `portfolio.html`, the only difference being the `site.data....portfolio....` is replacted with `site.data....applications....` or `site.data....videos....`.
I use [jekyll-serve](https://hub.docker.com/r/bretfisher/jekyll-serve/) and run `docker run -p 4000:4000 -v $(pwd):/site jekyll-serve
`  under the directory containing the `Gemfile`. 

### The problem
The `videos` in my website have the markdown files of the `applications`. 

The site is available [video-slider branch](https://github.com/xTent-robotics/xTent-robotics.github.io/tree/video-slider_ash)

Any help would be appreciated
Thanks
